name: Delete all containers from repository without tags

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 3 */6 *"

jobs:
  CleanUp:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.PKG_GITHUB_25 }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user
