name: Update Container Description

on:
  # Triggers on `README.md` update on `main`
  push:
    branches: [ main ]
    paths:
     - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/drupal-devcontainer
          provider: dockerhub
          short_description: 'Docker dev-container for Drupal development based of Microsoft PHP image'
          readme_file: 'README.md'
