name: Update Container Description

on:
  # Triggers on `README.md` update on `main`
  push:
    branches: [main]
    paths:
      - "README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest

    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: push README to Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: alchatti/drupal-devcontainer
          short-description: "Docker dev-container for Drupal development based of Microsoft PHP image"
